### ISSUE TITLE
Why an other bunch ?

### ISSUE THREAD

**Issue by femtotrader** [F483/neobunch#2]
Hello,

you might have a look at https://github.com/dsc/bunch/issues/32

An other bunch version which supports Python 2 and 3 exists
https://github.com/Infinidat/munch by @vmalloc from @Infinidat

Maybe this kind of package should belongs to an organization to avoid same result than dsc/bunch.

Kind regards

**Comment by vmalloc** [comment]
As I wrote in the linked issue, *munch* is currently watched by several Python developers at Infinidat, and is actively used by us in production, so I don't think it would suffer the same fate as bunch, since there are multiple people in charge.

**Comment by F483** [comment]
I was not aware of munch until after I ported bunch. I will take a closer look at munch in the coming days and merge with munch if I think it makes sense.

**Comment by F483** [comment]
@vmalloc I will very likely merge this with munch in the next weeks and discontinue neobunch.

**Comment by vmalloc** [comment]
@F483 that is great news! let us know if we can help somehow
