### ISSUE TITLE
Why so bad names?

### ISSUE THREAD

**Issue by buriy** [F483/neobunch#3]
neobunch, neobunchify -- don't you think they are just awful names?

This concept is known as attrdict for several decades.
https://pypi.python.org/pypi/attrdict
https://github.com/mewwts/addict
http://code.activestate.com/recipes/576972-attrdict/

We understood that you like to express you creativity, but please add links to other implementation of the same concept.
Community fragmentation (when person 1 uses lib1, person 2 uses lib 2 doing the same) is bad.

**Comment by F483** [comment]
I will very likely merge this lib with much, as I was not aware of its existence.
